##########################################################################
########Property Files controlled by External docker-compose file#########
app:
  name: Acumos_Portal

server:
  port: 8085
  address: 127.0.0.1

zuul:
  host: 
    connect-timeout-millis : 180000
    socket-timeout-millis : 180000
  routes:
    api:
      path: /api/**
      sensitiveHeaders:
      url: http://localhost:8083
    cmnt:
      path: /cmnt/**
      url: http://localhost:8087
      sensitiveHeaders:
    dsce:
      path: /dsce/**
      url: http://cognita-dev1-vm01-core.eastus.cloudapp.azure.com:8088
      sensitiveHeaders:
    site:
      path: /site/**
      url: http://localhost:9080
      stripPrefix: false
      sensitiveHeaders:
    azure:
      path: /azure/**
      url: http://localhost:9081
      stripPrefix: false
      sensitiveHeaders:
spring:
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

